version: 0.2
env:
  variables:
    S3_BUCKET: myCloudformationBucket
    REGION: eu-central-1
phases:
  build:
    commands:
      - echo "Packaging CloudFormation nested stacks.."
      - aws cloudformation package --region $REGION --template-file mainTemplate.yaml --s3-bucket $S3_BUCKET --output-template-file packaged.yml
      - echo "Done."
artifacts:
  files:
    - packaged.yml
    - parameters/*.json