version: 0.2

env:
  variables:
    GIT_REMOTE: "https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/datahubui"

  parameter-store:
    REMOTE_ACCOUNT: "/datahub/prod/aws/accountid"
    REMOTE_ROLE: "/datahub/prod/aws/role"

phases:
  pre_build:
    commands:
      - npm install
      - GENERATE_SOURCEMAP=false REACT_APP_STAGE=prod npm run build
      - yum -y install jq
      - aws sts get-caller-identity
      - make assume-role REMOTE_ROLE=$REMOTE_ROLE REMOTE_ACCOUNT=REMOTE_ACCOUNT
      - . ./.env.assumed_role
      - aws sts get-caller-identity
  build:
    commands:
      - DATAHUBUI_BUCKET=`aws ssm get-parameter --name /datahub/ui/prod/bucket --output text --query 'Parameter.Value'`
      - DATAHUBUI_DISTRIBUTION=`aws ssm get-parameter --name /datahub/ui/prod/distribution --output text --query 'Parameter.Value'`
      - aws s3 cp --recursive --acl public-read ./build s3://$DATAHUBUI_BUCKET/
      - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/service-worker.js s3://$DATAHUBUI_BUCKET/
      - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/index.html s3://$DATAHUBUI_BUCKET/
      - aws cloudfront create-invalidation --distribution-id $DATAHUBUI_DISTRIBUTION --paths /index.html /service-worker.js


artifacts:
  files:
    - '**/*'
