AWSTemplateFormatVersion: 2010-09-09
Description: >
  Resources for hosting Data Hub webapp on AWS S3 and  CloudFront

###############################################################################
Parameters:
###############################################################################

  EnvironmentName:
    Type: String
    AllowedValues:
      - staging
      - prod
    ConstraintDescription: Select, 'staging', 'prod'

###############################################################################
Conditions:
###############################################################################

  IsProdEnvironment: !Equals [!Ref EnvironmentName, prod]

###############################################################################
Resources:
###############################################################################

  webAppBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub datahub-cloudfront-origin-${EnvironmentName}-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          -
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: datahub

  webAppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref webAppBucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Sub ${webAppBucket.Arn}/*
            Principal:
              CanonicalUser: !GetAtt webAppCloudFrontOriginAccessId.S3CanonicalUserId
          - Action:
              - 's3:DeleteBucket'
            Effect: Deny
            Resource: !GetAtt webAppBucket.Arn
            Principal: "*"

  loggingBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub datahub-cloudfront-logs-${EnvironmentName}-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          -
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: datahub

  webAppCloudFrontOriginAccessId:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'CloudFront OAI for ${EnvironmentName}'

  webAppCloudFrontDistro:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !GetAtt webAppBucket.DomainName
          Id: webappOrigin
          S3OriginConfig:
            OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${webAppCloudFrontOriginAccessId}
        Enabled: true
        DefaultRootObject: index.html
        HttpVersion: http2
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          TargetOriginId: webappOrigin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
        Comment: !Sub webapp-${EnvironmentName}
        CustomErrorResponses:
        - ErrorCode: 403
          ResponseCode: 200
          ResponsePagePath: /index.html
        - ErrorCode: 404
          ResponseCode: 200
          ResponsePagePath: /index.html
        PriceClass: !If [IsProdEnvironment, PriceClass_All, PriceClass_100]
        Logging:
            Bucket : !Join [ "", [ !Ref loggingBucket, ".s3.amazonaws.com" ] ]
            IncludeCookies : false
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: datahub

  DatahubUIParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub '/datahub/ui/${EnvironmentName}/bucket'
      Type: String
      Value: !Sub 'datahub-cloudfront-origin-${EnvironmentName}'
      Tags:
        "Environment": !Ref EnvironmentName
        "Application": datahub

  DatahubDistribParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub '/datahub/ui/${EnvironmentName}/distribution'
      Type: String
      Value: !Sub ${webAppCloudFrontDistro}
      Tags:
        "Environment": !Ref EnvironmentName
        "Application": datahub

###############################################################################
Outputs:
###############################################################################

  BucketName:
    Value: !Ref webAppBucket
  LoggingBucketName:
    Value: !Ref loggingBucket
  DistroId:
    Value: !Ref webAppCloudFrontDistro
  DistroDomainName:
    Value: !GetAtt webAppCloudFrontDistro.DomainName
